#!/bin/bash

# Check if organization is provided as an argument
if [ -z "$1" ]; then
  echo "Usage: $0 <organization>"
  exit 1
fi

# Assign the organization name
org="$1"

# Print header
echo ""
echo "************ GitHub Dork Links for Organization: $org *******************"

# Define an array of sensitive keywords
keywords=(
"password"
"npmrc _auth"
"dockercfg"
"pem private"
"id_rsa"
"aws_access_key_id"
"s3cfg"
"htpasswd"
"git-credentials"
"bashrc password"
"sshd_config"
"xoxp OR xoxb OR xoxa"
"SECRET_KEY"
"client_secret"
"github_token"
"api_key"
"FTP"
"app_secret"
"passwd"
"s3.yml"
".env"
".exs"
"beanstalkd.yml"
"deploy.rake"
"mysql"
"credentials"
"PWD"
".bash_history"
".sls"
"secrets"
"composer.json"
"PRIVATE_KEY"
"PRIVATE"
"ENCRYPTION_KEY"
"ENCRYPT_KEY"
"KEYSTORE_PASSWORD"
"JWT_SECRET"
"OAUTH_CLIENT_SECRET"
"API_SECRET"
"AWS_SECRET_ACCESS_KEY"
"GCP_SERVICE_ACCOUNT"
"GCP_PRIVATE_KEY"
"AZURE_STORAGE_KEY"
"AZURE_TENANT_ID"
"AZURE_SUBSCRIPTION_ID"
"AZURE_CLIENT_SECRET"
"DO_ACCESS_TOKEN"
"FLASK_SECRET_KEY"
"DJANGO_SECRET_KEY"
"RUBY_SECRET_KEY"
"NODE_ENV"
"DEBUG"
"SECRET_KEY_BASE"
"SESSION_SECRET"
"WEBPACK_SECRET"
"MONGO_URI"
"REDIS_URL"
"DATABASE_URL"
"POSTGRES_PASSWORD"
"PGPASSWORD"
"SQLALCHEMY_DATABASE_URI"
"PAYPAL_CLIENT_ID"
"PAYPAL_CLIENT_SECRET"
"STRIPE_PUBLIC_KEY"
"STRIPE_SECRET_KEY"
"BRAINTREE_MERCHANT_ID"
"BRAINTREE_PRIVATE_KEY"
"DEBUG_PASSWORD"
"ERROR_LOG"
"ACCESS_LOG"
"CRASH_LOG"
"USER_CREDENTIALS"
"PRIVATE_CONFIG"
"PRIVATE_INFO"
"AUTHORIZATION_HEADER"
"AUTHORIZATION"
"SSO_TOKEN"
"LDAP_PASSWORD"
"LDAP_SECRET"
"TWITTER_API_KEY"
"FACEBOOK_API_SECRET"
"GOOGLE_CLIENT_ID"
"GOOGLE_CLIENT_SECRET"
"MICROSOFT_APP_ID"
"MICROSOFT_APP_SECRET"
"ZENDESK_API_KEY"
"MAILGUN_API_KEY"
"MQTT_TOKEN"
"STEAM_API_KEY"
".crt"
".cer"
".p7b"
".jks"
".ovpn"
".keychain"
)

# Loop through the keywords and generate GitHub search URLs
for keyword in "${keywords[@]}"; do
  echo "https://github.com/search?q=org%3A$org%20$keyword&type=Code"
done
